import Head from 'next/head'
import Image from 'next/image'

import Header from '../src/components/Header'
import Footer from '../src/components/Footer'
import ZIPWidget from '../src/components/ZIPWidget'
import WeatherWidget from '../src/components/WeatherWidget'

import styles from '../src/styles/Home.module.scss'
import bg from '../public/img/bg.jpeg'

export default function Home() {
  return (
    <div className='root'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.bg}>
        <Image src={bg} layout='fill' objectFit='cover' objectPosition='bottom' placeholder='blur' />
      </div>

      <Header title="getWeatherByZIPCode()" />

      <main className={styles.main}>
        <div className={styles.row}>
          <ZIPWidget />
          <WeatherWidget />
        </div>
      </main>

      <Footer />
    </div>
  )
}
